// Curated dataset of 35 popular Indian Government Schemes with real eligibility criteria
// Sources: myscheme.gov.in, india.gov.in, ministry websites

export const SCHEMES = [
    {
        id: 'pm-kisan',
        name: 'PM Kisan Samman Nidhi',
        ministry: 'Ministry of Agriculture & Farmers Welfare',
        category: 'Farmer',
        schemeType: 'Direct Cash Transfer',
        benefit: '\u20b96,000/year in 3 equal installments of \u20b92,000',
        description: 'Income support to all landholding farmer families across the country to supplement their financial needs for procuring various inputs related to agriculture and allied activities.',
        eligibility: {
            occupation: ['Farmer'],
            ageMin: 18,
            ageMax: null,
            incomeMax: null,
            categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
            states: 'all',
            area: ['Rural', 'Urban'],
            notes: 'Must be a landholding farmer family. Institutional landholders excluded. Higher income tax payers excluded.'
        },
        deadline: 'Open year-round',
        status: 'Open',
        popularity: 98,
        applications: 11000000,
        applyUrl: 'https://pmkisan.gov.in',
        documents: ['Aadhaar Card', 'Land Records', 'Bank Account Details']
    },
    {
        id: 'pmay-g',
        name: 'Pradhan Mantri Awas Yojana - Gramin',
        ministry: 'Ministry of Rural Development',
        category: 'Housing',
        schemeType: 'Subsidy',
        benefit: '\u20b91.20-1.30 Lakh financial assistance for house construction',
        description: 'Aims to provide a pucca house with basic amenities to all houseless householder and those households living in kutcha and dilapidated house in rural areas by 2024.',
        eligibility: {
            occupation: 'any',
            ageMin: 18,
            ageMax: null,
            incomeMax: 300000,
            categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
            states: 'all',
            area: ['Rural'],
            notes: 'Houseless or living in 0/1/2 room kutcha house. Priority for SC/ST, minorities, women.'
        },
        deadline: '31 Dec 2025',
        status: 'Open',
        popularity: 95,
        applications: 8500000,
        applyUrl: 'https://pmayg.nic.in',
        documents: ['Aadhaar Card', 'Income Certificate', 'Caste Certificate', 'Bank Details', 'Ration Card']
    },
    {
        id: 'pmay-u',
        name: 'Pradhan Mantri Awas Yojana - Urban',
        ministry: 'Ministry of Housing & Urban Affairs',
        category: 'Housing',
        schemeType: 'Subsidy',
        benefit: 'Interest subsidy up to \u20b92.67 Lakh on home loans',
        description: 'Affordable housing for urban poor with credit-linked interest subsidy.',
        eligibility: { occupation: 'any', ageMin: 21, ageMax: 70, incomeMax: 1800000, categories: ['General', 'OBC', 'SC', 'ST', 'EWS'], states: 'all', area: ['Urban'], notes: 'EWS up to \u20b93L, LIG up to \u20b96L, MIG-I \u20b912L, MIG-II \u20b918L annual income.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 90,
        applications: 7800000,
        applyUrl: 'https://pmaymis.gov.in',
        documents: ['Aadhaar Card', 'Income Certificate', 'Address Proof', 'Bank Statement']
    },
    {
        id: 'ayushman-bharat',
        name: 'Ayushman Bharat - PMJAY',
        ministry: 'Ministry of Health & Family Welfare',
        category: 'Health',
        schemeType: 'Insurance',
        benefit: 'Health cover of \u20b95 Lakh per family per year',
        description: 'World\u2019s largest health assurance scheme providing free secondary and tertiary care hospitalization to 12 crore poor and vulnerable families.',
        eligibility: { occupation: 'any', ageMin: 0, ageMax: null, incomeMax: 250000, categories: ['General', 'OBC', 'SC', 'ST', 'EWS'], states: 'all', area: ['Rural', 'Urban'], notes: 'Based on SECC-2011 deprivation criteria. Auto-enrolled families.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 97,
        applications: 50000000,
        applyUrl: 'https://pmjay.gov.in',
        documents: ['Aadhaar Card', 'Ration Card', 'SECC verification']
    },
    {
        id: 'sukanya-samriddhi',
        name: 'Sukanya Samriddhi Yojana',
        ministry: 'Ministry of Finance',
        category: 'Women',
        schemeType: 'Savings',
        benefit: '8.2% interest, tax-free returns for girl child savings',
        description: 'Small savings scheme for girl children. Account opened in the name of girl child below 10 years.',
        eligibility: { occupation: 'any', ageMin: 0, ageMax: 10, incomeMax: null, categories: ['General', 'OBC', 'SC', 'ST', 'EWS'], states: 'all', area: ['Rural', 'Urban'], notes: 'Only for girl children below 10 years. Parent/Guardian opens account.', gender: 'Female' },
        deadline: 'Open',
        status: 'Open',
        popularity: 92,
        applications: 3500000,
        applyUrl: 'https://www.indiapost.gov.in',
        documents: ['Girl child Birth Certificate', 'Parent Aadhaar', 'Address Proof']
    },
    {
        id: 'nsp-pre-matric',
        name: 'National Scholarship - Pre-Matric (SC/ST/OBC)',
        ministry: 'Ministry of Social Justice & Empowerment',
        category: 'Student',
        schemeType: 'Scholarship',
        benefit: '\u20b9225-750/month for 10 months + book allowance',
        description: 'Pre-matric scholarship for students of SC/ST/OBC studying in class 9-10.',
        eligibility: { occupation: ['Student'], ageMin: 13, ageMax: 18, incomeMax: 250000, categories: ['SC', 'ST', 'OBC'], states: 'all', area: ['Rural', 'Urban'], education: ['School Student'], notes: 'Family income < \u20b92.5 Lakh. Currently studying in class 9 or 10.' },
        deadline: '31 Oct 2025',
        status: 'Open',
        popularity: 88,
        applications: 4200000,
        applyUrl: 'https://scholarships.gov.in',
        documents: ['Aadhaar Card', 'Income Certificate', 'Caste Certificate', 'Bonafide Certificate', 'Bank Details']
    },
    {
        id: 'nsp-post-matric',
        name: 'National Scholarship - Post-Matric',
        ministry: 'Ministry of Social Justice & Empowerment',
        category: 'Student',
        schemeType: 'Scholarship',
        benefit: 'Tuition fee + maintenance allowance \u20b9230-1200/month',
        description: 'For students of SC/ST/OBC/Minority pursuing higher studies post-class 10.',
        eligibility: { occupation: ['Student'], ageMin: 15, ageMax: 35, incomeMax: 250000, categories: ['SC', 'ST', 'OBC', 'EWS'], states: 'all', area: ['Rural', 'Urban'], education: ['College Student', 'Diploma', 'Graduate', 'Postgraduate'], notes: 'Family income < \u20b92.5 Lakh.' },
        deadline: '31 Oct 2025',
        status: 'Open',
        popularity: 94,
        applications: 6700000,
        applyUrl: 'https://scholarships.gov.in',
        documents: ['Aadhaar Card', 'Income Certificate', 'Caste Certificate', 'Previous Marksheet', 'Fee Receipt', 'Bank Details']
    },
    {
        id: 'inspire-scholarship',
        name: 'INSPIRE Scholarship for Higher Education',
        ministry: 'Department of Science & Technology',
        category: 'Student',
        schemeType: 'Scholarship',
        benefit: '\u20b980,000/year for BSc/MSc students',
        description: 'Scholarship to attract talent to study basic and natural sciences at BSc, BS, Integrated MSc/MS level.',
        eligibility: { occupation: ['Student'], ageMin: 17, ageMax: 22, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'], education: ['College Student'], notes: 'Top 1% in Class XII Board or Top 10K in JEE/NEET. Must pursue Natural/Basic Sciences.' },
        deadline: '30 Sep 2025',
        status: 'Open',
        popularity: 78,
        applications: 150000,
        applyUrl: 'https://online-inspire.gov.in',
        documents: ['Aadhaar Card', '12th Marksheet', 'Bonafide Certificate', 'Bank Details']
    },
    {
        id: 'startup-india-seed',
        name: 'Startup India Seed Fund Scheme (SISFS)',
        ministry: 'DPIIT, Ministry of Commerce',
        category: 'Startup',
        schemeType: 'Grant',
        benefit: 'Up to \u20b920 Lakh grant + \u20b950 Lakh debt/convertible debt',
        description: 'Financial assistance to startups for proof of concept, prototype development, product trials, market entry and commercialization.',
        eligibility: { occupation: ['Startup Founder', 'Business Owner'], ageMin: 18, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'], notes: 'DPIIT-recognized startup, incorporated less than 2 years. Idea-stage startups eligible.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 86,
        applications: 45000,
        applyUrl: 'https://seedfund.startupindia.gov.in',
        documents: ['DPIIT Recognition', 'Incorporation Certificate', 'PAN', 'Pitch Deck']
    },
    {
        id: 'mudra-loan',
        name: 'Pradhan Mantri MUDRA Yojana (PMMY)',
        ministry: 'Ministry of Finance',
        category: 'Employment',
        schemeType: 'Loan',
        benefit: 'Loans up to \u20b910 Lakh (Shishu/Kishore/Tarun categories)',
        description: 'Collateral-free loans for non-corporate, non-farm small/micro enterprises.',
        eligibility: { occupation: ['Business Owner', 'Startup Founder', 'Unemployed'], ageMin: 18, ageMax: 65, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'], notes: 'Indian citizen with viable business plan in non-farm sector.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 93,
        applications: 41000000,
        applyUrl: 'https://www.mudra.org.in',
        documents: ['Aadhaar Card', 'PAN', 'Business Plan', 'Bank Statement', 'Address Proof']
    },
    {
        id: 'standup-india',
        name: 'Stand-Up India Scheme',
        ministry: 'Department of Financial Services',
        category: 'Women',
        schemeType: 'Loan',
        benefit: 'Bank loans \u20b910 Lakh to \u20b91 Crore for SC/ST/Women entrepreneurs',
        description: 'Facilitate bank loans for setting up greenfield enterprises by SC/ST and Women entrepreneurs.',
        eligibility: { occupation: ['Business Owner', 'Startup Founder'], ageMin: 18, ageMax: null, incomeMax: null, categories: ['SC', 'ST'], gender: 'any', states: 'all', area: ['Rural', 'Urban'], notes: 'SC/ST OR Woman entrepreneur, >51% shareholding, greenfield project.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 82,
        applications: 180000,
        applyUrl: 'https://www.standupmitra.in',
        documents: ['Aadhaar Card', 'Caste Certificate', 'Business Plan', 'PAN']
    },
    {
        id: 'pmsby',
        name: 'Pradhan Mantri Suraksha Bima Yojana',
        ministry: 'Ministry of Finance',
        category: 'Health',
        schemeType: 'Insurance',
        benefit: '\u20b92 Lakh accidental death/disability cover for \u20b920/year',
        description: 'Affordable accident insurance scheme for masses.',
        eligibility: { occupation: 'any', ageMin: 18, ageMax: 70, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'], notes: 'Must have savings bank account with auto-debit consent.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 89,
        applications: 47000000,
        applyUrl: 'https://www.jansuraksha.gov.in',
        documents: ['Aadhaar Card', 'Bank Account']
    },
    {
        id: 'pmjjby',
        name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana',
        ministry: 'Ministry of Finance',
        category: 'Health',
        schemeType: 'Insurance',
        benefit: '\u20b92 Lakh life cover for \u20b9436/year',
        description: 'Life insurance scheme offering renewable annual life cover.',
        eligibility: { occupation: 'any', ageMin: 18, ageMax: 50, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'] },
        deadline: 'Open',
        status: 'Open',
        popularity: 84,
        applications: 16000000,
        applyUrl: 'https://www.jansuraksha.gov.in',
        documents: ['Aadhaar Card', 'Bank Account']
    },
    {
        id: 'apy',
        name: 'Atal Pension Yojana',
        ministry: 'PFRDA, Ministry of Finance',
        category: 'Senior Citizen',
        schemeType: 'Pension',
        benefit: 'Guaranteed pension of \u20b91,000-5,000/month from age 60',
        description: 'Pension scheme focused on unorganized sector workers.',
        eligibility: { occupation: 'any', ageMin: 18, ageMax: 40, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'], notes: 'Not an income-tax payer. Must have bank account.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 80,
        applications: 6800000,
        applyUrl: 'https://www.npscra.nsdl.co.in',
        documents: ['Aadhaar Card', 'Bank Account']
    },
    {
        id: 'iggvy-disability',
        name: 'Indira Gandhi National Disability Pension Scheme',
        ministry: 'Ministry of Rural Development',
        category: 'Disability',
        schemeType: 'Pension',
        benefit: '\u20b9300-500/month pension',
        description: 'Monthly pension to persons with severe/multiple disabilities below poverty line.',
        eligibility: { occupation: 'any', ageMin: 18, ageMax: 79, incomeMax: 100000, categories: 'all', states: 'all', area: ['Rural', 'Urban'], disability: true, notes: 'BPL family with severe (80%+) disability.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 71,
        applications: 1200000,
        applyUrl: 'https://nsap.nic.in',
        documents: ['Aadhaar Card', 'Disability Certificate', 'BPL Card', 'Bank Details']
    },
    {
        id: 'iggopy-elderly',
        name: 'Indira Gandhi National Old Age Pension Scheme',
        ministry: 'Ministry of Rural Development',
        category: 'Senior Citizen',
        schemeType: 'Pension',
        benefit: '\u20b9200-500/month (60+) | \u20b9500-1000/month (80+)',
        description: 'Monthly pension to elderly persons below poverty line.',
        eligibility: { occupation: 'any', ageMin: 60, ageMax: null, incomeMax: 100000, categories: 'all', states: 'all', area: ['Rural', 'Urban'], notes: 'BPL family. Age 60+.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 87,
        applications: 23000000,
        applyUrl: 'https://nsap.nic.in',
        documents: ['Aadhaar Card', 'Age Proof', 'BPL Card', 'Bank Details']
    },
    {
        id: 'iggwpsy-widow',
        name: 'Indira Gandhi National Widow Pension Scheme',
        ministry: 'Ministry of Rural Development',
        category: 'Women',
        schemeType: 'Pension',
        benefit: '\u20b9300-500/month pension',
        description: 'Monthly pension to widows below poverty line.',
        eligibility: { occupation: 'any', ageMin: 40, ageMax: 79, incomeMax: 100000, categories: 'all', gender: 'Female', states: 'all', area: ['Rural', 'Urban'], notes: 'BPL widow aged 40-79.', maritalStatus: 'Widowed' },
        deadline: 'Open',
        status: 'Open',
        popularity: 76,
        applications: 6300000,
        applyUrl: 'https://nsap.nic.in',
        documents: ['Aadhaar Card', 'Husband Death Certificate', 'BPL Card', 'Bank Details']
    },
    {
        id: 'pmkvy',
        name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)',
        ministry: 'Ministry of Skill Development',
        category: 'Employment',
        schemeType: 'Training',
        benefit: 'Free skill training + certification + placement support',
        description: 'Skill training to youth in various trades to enhance employability.',
        eligibility: { occupation: ['Unemployed', 'Student'], ageMin: 15, ageMax: 45, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'], notes: 'Indian nationals, school dropouts or unemployed youth.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 91,
        applications: 14000000,
        applyUrl: 'https://www.pmkvyofficial.org',
        documents: ['Aadhaar Card', 'Education Certificate', 'Bank Details']
    },
    {
        id: 'pmegp',
        name: 'Prime Minister Employment Generation Programme',
        ministry: 'Ministry of MSME',
        category: 'Employment',
        schemeType: 'Loan',
        benefit: '15-35% subsidy on project cost up to \u20b950 Lakh (mfg) / \u20b920 Lakh (service)',
        description: 'Credit-linked subsidy scheme for setting up new micro enterprises and generating employment in rural and urban areas.',
        eligibility: { occupation: ['Unemployed', 'Business Owner', 'Startup Founder'], ageMin: 18, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'], education: ['School Student', 'Diploma', 'Graduate'], notes: 'Min 8th pass for projects > \u20b910 Lakh (mfg) / \u20b95 Lakh (service).' },
        deadline: 'Open',
        status: 'Open',
        popularity: 79,
        applications: 900000,
        applyUrl: 'https://www.kviconline.gov.in/pmegpeportal',
        documents: ['Aadhaar Card', 'Education Certificate', 'Project Report', 'Caste Certificate (if applicable)']
    },
    {
        id: 'pm-vishwakarma',
        name: 'PM Vishwakarma Scheme',
        ministry: 'Ministry of MSME',
        category: 'Employment',
        schemeType: 'Loan',
        benefit: 'Tools incentive \u20b915k + loans up to \u20b93 Lakh @5% + training',
        description: 'Support to traditional artisans and craftspeople in 18 trades.',
        eligibility: { occupation: ['Business Owner', 'Unemployed'], ageMin: 18, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'], notes: '18 listed trades like carpenter, blacksmith, potter, tailor, barber etc.' },
        deadline: '31 Mar 2028',
        status: 'Open',
        popularity: 85,
        applications: 2400000,
        applyUrl: 'https://pmvishwakarma.gov.in',
        documents: ['Aadhaar Card', 'Mobile Number', 'Bank Details', 'Ration Card']
    },
    {
        id: 'pm-svanidhi',
        name: 'PM SVANidhi (Street Vendor Loan)',
        ministry: 'Ministry of Housing & Urban Affairs',
        category: 'Employment',
        schemeType: 'Loan',
        benefit: 'Working capital loan up to \u20b950,000 + 7% interest subsidy',
        description: 'Micro-credit to street vendors to resume their livelihoods affected by COVID-19.',
        eligibility: { occupation: ['Business Owner'], ageMin: 18, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Urban'], notes: 'Urban street vendors with Certificate of Vending or ULB ID.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 77,
        applications: 5800000,
        applyUrl: 'https://pmsvanidhi.mohua.gov.in',
        documents: ['Aadhaar Card', 'Certificate of Vending', 'Bank Account']
    },
    {
        id: 'beti-bachao',
        name: 'Beti Bachao Beti Padhao',
        ministry: 'Ministry of Women & Child Development',
        category: 'Women',
        schemeType: 'Welfare',
        benefit: 'Education incentives, sex-ratio improvement programs',
        description: 'Campaign to address declining child sex ratio and empower girl child.',
        eligibility: { occupation: 'any', ageMin: 0, ageMax: 18, incomeMax: null, categories: 'all', gender: 'Female', states: 'all', area: ['Rural', 'Urban'] },
        deadline: 'Open',
        status: 'Open',
        popularity: 88,
        applications: 0,
        applyUrl: 'https://wcd.nic.in',
        documents: ['Birth Certificate', 'Aadhaar Card']
    },
    {
        id: 'janani-suraksha',
        name: 'Janani Suraksha Yojana',
        ministry: 'Ministry of Health & Family Welfare',
        category: 'Women',
        schemeType: 'Direct Cash Transfer',
        benefit: '\u20b91,400 (rural) / \u20b91,000 (urban) cash assistance for institutional delivery',
        description: 'Cash assistance for institutional deliveries to reduce maternal and infant mortality.',
        eligibility: { occupation: 'any', ageMin: 18, ageMax: null, incomeMax: 100000, categories: 'all', gender: 'Female', states: 'all', area: ['Rural', 'Urban'], notes: 'Pregnant women from BPL families. LPS states all pregnant women.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 90,
        applications: 10500000,
        applyUrl: 'https://nhm.gov.in',
        documents: ['JSY Card', 'Aadhaar', 'BPL Card', 'Bank Details']
    },
    {
        id: 'mgnrega',
        name: 'MGNREGA - Mahatma Gandhi NREGA',
        ministry: 'Ministry of Rural Development',
        category: 'Employment',
        schemeType: 'Employment',
        benefit: '100 days of guaranteed wage employment per year',
        description: 'Guarantees 100 days of wage employment in a financial year to a rural household.',
        eligibility: { occupation: 'any', ageMin: 18, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Rural'], notes: 'Adult member of rural household willing to do unskilled manual work.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 96,
        applications: 158000000,
        applyUrl: 'https://nrega.nic.in',
        documents: ['Aadhaar Card', 'Job Card', 'Bank Account']
    },
    {
        id: 'soil-health-card',
        name: 'Soil Health Card Scheme',
        ministry: 'Ministry of Agriculture',
        category: 'Farmer',
        schemeType: 'Subsidy',
        benefit: 'Free soil testing & crop-wise nutrient recommendations',
        description: 'Soil testing and nutrient recommendations every 3 years to all farmers.',
        eligibility: { occupation: ['Farmer'], ageMin: 18, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Rural'] },
        deadline: 'Open',
        status: 'Open',
        popularity: 72,
        applications: 230000000,
        applyUrl: 'https://soilhealth.dac.gov.in',
        documents: ['Aadhaar Card', 'Land Records']
    },
    {
        id: 'kcc',
        name: 'Kisan Credit Card (KCC)',
        ministry: 'Ministry of Agriculture',
        category: 'Farmer',
        schemeType: 'Loan',
        benefit: 'Crop loan up to \u20b93 Lakh @ 4% (with subvention)',
        description: 'Short-term credit to farmers for cultivation expenses, post-harvest, allied activities.',
        eligibility: { occupation: ['Farmer'], ageMin: 18, ageMax: 75, incomeMax: null, categories: 'all', states: 'all', area: ['Rural'] },
        deadline: 'Open',
        status: 'Open',
        popularity: 92,
        applications: 76000000,
        applyUrl: 'https://www.pmkisan.gov.in/Documents/KCC.pdf',
        documents: ['Aadhaar Card', 'Land Records', 'PAN', 'Bank Account']
    },
    {
        id: 'pmfby',
        name: 'Pradhan Mantri Fasal Bima Yojana',
        ministry: 'Ministry of Agriculture',
        category: 'Farmer',
        schemeType: 'Insurance',
        benefit: 'Crop insurance, premium 1.5%-5%',
        description: 'Insurance to farmers against crop loss due to natural calamities, pests and diseases.',
        eligibility: { occupation: ['Farmer'], ageMin: 18, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Rural'] },
        deadline: 'Seasonal (Kharif/Rabi)',
        status: 'Open',
        popularity: 85,
        applications: 55000000,
        applyUrl: 'https://pmfby.gov.in',
        documents: ['Aadhaar', 'Land Records', 'Sowing Certificate', 'Bank Account']
    },
    {
        id: 'pli-scheme',
        name: 'Production Linked Incentive (PLI) Scheme',
        ministry: 'DPIIT',
        category: 'Startup',
        schemeType: 'Subsidy',
        benefit: '4-6% incentive on incremental sales for 5 years',
        description: 'Incentives for incremental sales of products manufactured in India in 14 key sectors.',
        eligibility: { occupation: ['Business Owner', 'Startup Founder'], ageMin: 18, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'], notes: 'Registered Indian manufacturing companies in 14 PLI sectors.' },
        deadline: 'Sector-specific',
        status: 'Open',
        popularity: 70,
        applications: 2000,
        applyUrl: 'https://dpiit.gov.in',
        documents: ['Company Registration', 'GST', 'Manufacturing License']
    },
    {
        id: 'skill-india-digital',
        name: 'Skill India Digital',
        ministry: 'Ministry of Skill Development',
        category: 'Student',
        schemeType: 'Training',
        benefit: 'Free online courses + certification in 100+ skills',
        description: 'Digital platform for skilling, reskilling and upskilling for jobs and entrepreneurship.',
        eligibility: { occupation: ['Student', 'Unemployed', 'Private Employee'], ageMin: 14, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'] },
        deadline: 'Open',
        status: 'Open',
        popularity: 75,
        applications: 3200000,
        applyUrl: 'https://www.skillindiadigital.gov.in',
        documents: ['Aadhaar Card']
    },
    {
        id: 'rashtriya-vayoshri',
        name: 'Rashtriya Vayoshri Yojana',
        ministry: 'Ministry of Social Justice & Empowerment',
        category: 'Senior Citizen',
        schemeType: 'Welfare',
        benefit: 'Free assistive aids (hearing aid, walking stick, wheelchair etc.)',
        description: 'Physical aids and assistive living devices to BPL senior citizens with age-related disabilities.',
        eligibility: { occupation: 'any', ageMin: 60, ageMax: null, incomeMax: 100000, categories: 'all', states: 'all', area: ['Rural', 'Urban'], notes: 'BPL senior citizens.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 68,
        applications: 480000,
        applyUrl: 'https://alimco.in',
        documents: ['Aadhaar Card', 'Age Proof', 'BPL Card', 'Medical Certificate']
    },
    {
        id: 'adip-scheme',
        name: 'ADIP - Assistance for Disabled Persons',
        ministry: 'Department of Empowerment of Persons with Disabilities',
        category: 'Disability',
        schemeType: 'Welfare',
        benefit: 'Free aids/appliances (hearing aids, wheelchairs, prosthetics)',
        description: 'Procurement and fitting of aids/appliances to persons with disabilities.',
        eligibility: { occupation: 'any', ageMin: 0, ageMax: null, incomeMax: 300000, categories: 'all', states: 'all', area: ['Rural', 'Urban'], disability: true },
        deadline: 'Open',
        status: 'Open',
        popularity: 73,
        applications: 1700000,
        applyUrl: 'https://disabilityaffairs.gov.in',
        documents: ['Aadhaar Card', 'Disability Certificate', 'Income Certificate']
    },
    {
        id: 'ujjwala-yojana',
        name: 'Pradhan Mantri Ujjwala Yojana (PMUY)',
        ministry: 'Ministry of Petroleum & Natural Gas',
        category: 'Women',
        schemeType: 'Subsidy',
        benefit: 'Free LPG connection + subsidized refills',
        description: 'Free cooking gas (LPG) connections to women from BPL families.',
        eligibility: { occupation: 'any', ageMin: 18, ageMax: null, incomeMax: 100000, categories: 'all', gender: 'Female', states: 'all', area: ['Rural', 'Urban'], notes: 'BPL women without existing LPG connection.' },
        deadline: 'Open',
        status: 'Open',
        popularity: 94,
        applications: 96000000,
        applyUrl: 'https://pmuy.gov.in',
        documents: ['Aadhaar Card', 'BPL Card', 'Bank Account']
    },
    {
        id: 'pmjdy',
        name: 'Pradhan Mantri Jan Dhan Yojana',
        ministry: 'Ministry of Finance',
        category: 'Employment',
        schemeType: 'Welfare',
        benefit: 'Zero-balance account + \u20b92L accident insurance + \u20b910k overdraft',
        description: 'Financial inclusion mission for affordable access to banking, credit, insurance, and pension.',
        eligibility: { occupation: 'any', ageMin: 10, ageMax: null, incomeMax: null, categories: 'all', states: 'all', area: ['Rural', 'Urban'] },
        deadline: 'Open',
        status: 'Open',
        popularity: 95,
        applications: 530000000,
        applyUrl: 'https://pmjdy.gov.in',
        documents: ['Aadhaar Card']
    },
    {
        id: 'aikyashree',
        name: 'NMS Scholarship for Minorities (Pre & Post Matric)',
        ministry: 'Ministry of Minority Affairs',
        category: 'Student',
        schemeType: 'Scholarship',
        benefit: '\u20b91,000-12,000/year scholarship for minority students',
        description: 'Scholarships for students belonging to notified minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi).',
        eligibility: { occupation: ['Student'], ageMin: 5, ageMax: 30, incomeMax: 200000, categories: 'all', states: 'all', area: ['Rural', 'Urban'], education: ['School Student', 'College Student', 'Diploma', 'Graduate', 'Postgraduate'], notes: 'Belongs to notified minority community.' },
        deadline: '15 Oct 2025',
        status: 'Closing Soon',
        popularity: 81,
        applications: 2500000,
        applyUrl: 'https://scholarships.gov.in',
        documents: ['Aadhaar Card', 'Community Certificate', 'Income Certificate', 'Bonafide Certificate']
    }
];

export const CATEGORIES = [
    { id: 'Student', icon: 'GraduationCap', label: 'Student' },
    { id: 'Farmer', icon: 'Sprout', label: 'Farmer' },
    { id: 'Women', icon: 'HeartHandshake', label: 'Women' },
    { id: 'Housing', icon: 'Home', label: 'Housing' },
    { id: 'Employment', icon: 'Briefcase', label: 'Employment' },
    { id: 'Health', icon: 'Heart', label: 'Health' },
    { id: 'Startup', icon: 'Rocket', label: 'Startup' },
    { id: 'Senior Citizen', icon: 'Users', label: 'Senior Citizen' },
    { id: 'Disability', icon: 'Accessibility', label: 'Disability' }
];
